- name: leave docker swarm 
  docker_swarm:
    state: absent
    force: true

- name: swarm worker-two join
  docker_swarm:
    state: join
    advertise_addr: vm-worker-one
    join_token: "{{ hostvars['join_token']['value'] }}"
    remote_addrs: [ "vm-manager:2377" ] 

- name: swarm worker-one join
  docker_swarm:
    state: join
    advertise_addr: vm-worker-two
    join_token: "{{ hostvars['join_token']['value'] }}"
    remote_addrs: [ "vm-wmanager:2377" ] 